### ISSUE TITLE
Embedded in workbook query - The (maximum) expected data length is 8000, while the returned data length is 8832

### ISSUE THREAD

**Issue by Redrichmond** [isajediknight/Tableau-Server-Postgres-Queries#2]
workbooks QUERY - I had to comment out the embedded column

 --T301.embedded AS "Embedded (WB)", 

ERROR
The (maximum) expected data length is 8000, while the returned data length is 8832

**Comment by isajediknight** [comment]
Thanks for pointing this out!  Commented this field out as you did and added a comment.  Committed to master.
